# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Snow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'TGCoreKit', :git => 'https://github.com/Aaron0927/TGCoreKit.git'
  # Pods for Snow
  pod 'SnapKit'
  pod 'Kingfisher', '~> 7.0'
  pod 'lottie-ios'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Charts'
end
