# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Snow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Snow
  pod 'SnapKit'
  pod 'Kingfisher', '~> 7.0'
  pod 'lottie-ios'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Charts'
  
  pod 'JXSegmentedView' # 分类切换滚动视图
  pod 'JXPagingView/Paging'
end
